#pragma once
// libcmods - the c modules library
//
// libc

#include "common.h"
#include "modules/c.h"

const struct cmods_libc c = {
	// standard library
	.lib.malloc =		malloc,
	.lib.calloc =		calloc,
	.lib.realloc =		realloc,
	.lib.free =		free,

	.lib.atof =		atof,
	.lib.atoi =		atoi,
	.lib.atol =		atol,
	.lib.atoll =		atoll,
	.lib.strtod =		strtod,
	.lib.strtof =		strtof,
	.lib.strtol =		strtol,
	.lib.strtold =		strtold,
	.lib.strtoll =		strtoll,
	.lib.strtoul =		strtoul,
	.lib.strtoull =		strtoull,

	.lib.srand =		srand,
	.lib.rand =		rand,

	.lib.qsort =		qsort,
	.lib.bsearch =		bsearch,

	.lib.abort =		abort,
	.lib.atexit =		atexit,
	.lib.at_quick_exit =	at_quick_exit,
	.lib.exit =		exit,
	.lib.getenv =		getenv,
	.lib.quick_exit	=	quick_exit,
	.lib.system =		system,
	.lib._exit =		_Exit,

	.lib.mblen =		mblen,
	.lib.mbstowcs =		mbstowcs,
	.lib.mbtowc =		mbtowc,
	.lib.wcstombs =		wcstombs,
	.lib.wctomb =		wctomb,

	.lib.abs =		abs,
	.lib.div =		div,
	.lib.labs =		labs,
	.lib.ldiv =		ldiv,
	.lib.llabs =		llabs,
	.lib.lldiv =		lldiv,

	// IO
	.io.open =		fopen,
	.io.reopen =		freopen,
	.io.flush =		fflush,
	.io.close =		fclose,
	.io.setbuf =		setbuf,
	.io.setvbuf =		setvbuf,

	.io.rm =		remove,
	.io.mv =		rename,
	.io.tmpfile =		tmpfile,
	.io.tmpname =		tmpnam,

	.io.eof =		feof,
	.io.ferror =		ferror,
	.io.perror =		perror,
	.io.clearerr =		clearerr,

	.io.rewind =		rewind,
	.io.tell =		ftell,
	.io.seek =		fseek,
	.io.getpos =		fgetpos,
	.io.setpos =		fsetpos,

	.io.fgetc =		fgetc,
	.io.fgets =		fgets,
	.io.fputc =		fputc,
	.io.fputs =		fputs,
	.io.getc =		getc,
	.io.getchar =		getchar,
	.io.putc =		putc,
	.io.putchar =		putchar,
	.io.puts =		puts,
	.io.ungetc =		ungetc,

	.io.printf =		printf,
	.io.fprintf =		fprintf,
	.io.sprintf =		sprintf,
	.io.snprintf =		snprintf,
	.io.asprintf =		asprintf,
	.io.dprintf =		dprintf,
	.io.vprintf =		vprintf,
	.io.vfprintf =		vfprintf,
	.io.vsprintf =		vsprintf,
	.io.vsnprintf =		vsnprintf,
	.io.vasprintf =		vasprintf,
	.io.vdprintf =		vdprintf,

	.io.scanf =		scanf,
	.io.fscanf =		fscanf,
	.io.sscanf =		sscanf,
	.io.vscanf =		vscanf,
	.io.vfscanf =		vfscanf,
	.io.vsscanf =		vsscanf,

	// strings and memory
	.str.len =		strlen,
	.str.cat =		strcat,
	.str.ncat =		strncat,
	.str.error =		strerror,
	.str.xfrm =		strxfrm,

	.str.cpy =		strcpy,
	.str.ncpy =		strncpy,

	.str.cmp =		strcmp,
	.str.ncmp =		strncmp,
	.str.coll =		strcoll,

	.str.chr =		strchr,
	.str.rchr =		strrchr,
	.str.cspn =		strcspn,
	.str.spn =		strspn,
	.str.pbrk =		strpbrk,
	.str.str =		strstr,
	.str.tok =		strtok,

	.mem.set =		memset,

	.mem.cpy =		memcpy,
	.mem.move =		memmove,

	.mem.cmp =		memcmp,

	.mem.chr =		memchr,

	// single char type functions
	.type.tolower =		tolower,
	.type.toupper =		toupper,

	.type.isalnum =		isalnum,
	.type.isalpha =		isalpha,
	.type.isblank =		isblank,
	.type.iscntrl =		iscntrl,
	.type.isdigit =		isdigit,
	.type.isgraph =		isgraph,
	.type.islower =		islower,
	.type.isprint =		isprint,
	.type.ispunct =		ispunct,
	.type.isspace =		isspace,
	.type.isupper =		isupper,
	.type.isxdigit =	isxdigit,

	// locale
	.locale.localeconv =	localeconv,
	.locale.set =		setlocale,

	// signal handling
	.signal.signal =	signal,
	.signal.raise =		raise,

	// time
	.time.clock =		clock,
	.time.difftime =	difftime,
	.time.mktime =		mktime,
	.time.time =		time,

	.time.strftime =	strftime,
	.time.asctime =		asctime,
	.time.ctime =		ctime,
	.time.gmtime =		gmtime,
	.time.localtime =	localtime,

	// floating point environment
	.fenv.get =		fegetenv,
	.fenv.set =		fesetenv,
	.fenv.update =		feupdateenv,

	.fenv.round.get =	fegetround,
	.fenv.round.set =	fesetround,

	.fenv.except.hold =	feholdexcept,
	.fenv.except.clear =	feclearexcept,
	.fenv.except.raise =	feraiseexcept,

	.fenv.except.flag.get =	fegetexceptflag,
	.fenv.except.flag.set =	fesetexceptflag,

	// math
	.math.fabs =		fabs,
	.math.fabsf =		fabsf,
	.math.fabsl =		fabsl,
	.math.fmax =		fmax,
	.math.fmaxf =		fmaxf,
	.math.fmaxl =		fmaxl,
	.math.fmin =		fmin,
	.math.fminf =		fminf,
	.math.fminl =		fminl,
	.math.fdim =		fdim,
	.math.fdimf =		fdimf,
	.math.fdiml =		fdiml,
	.math.fma =		fma,
	.math.fmaf =		fmaf,
	.math.fmal =		fmal,
	.math.fmod =		fmod,
	.math.fmodf =		fmodf,
	.math.fmodl =		fmodl,
	.math.copysign =	copysign,
	.math.copysignf =	copysignf,
	.math.copysignl =	copysignl,
	.math.nan =		nan,
	.math.nanf =		nanf,
	.math.nanl =		nanl,
	.math.nextafter =	nextafter,
	.math.nextafterf =	nextafterf,
	.math.nextafterl =	nextafterl,
	.math.nexttoward =	nexttoward,
	.math.nexttowardf =	nexttowardf,
	.math.nexttowardl =	nexttowardl,
	.math.remainder =	remainder,
	.math.remainderf =	remainderf,
	.math.remainderl =	remainderl,
	.math.remquo =		remquo,
	.math.remquof =		remquof,
	.math.remquol =		remquol,

	.math.ceil =		ceil,
	.math.ceilf =		ceilf,
	.math.ceill =		ceill,
	.math.floor =		floor,
	.math.floorf =		floorf,
	.math.floorl =		floorl,
	.math.trunc =		trunc,
	.math.truncf =		truncf,
	.math.truncl =		truncl,
	.math.round =		round,
	.math.roundf =		roundf,
	.math.roundl =		roundl,
	.math.lround =		lround,
	.math.lroundf =		lroundf,
	.math.lroundl =		lroundl,
	.math.llround =		llround,
	.math.llroundf =	llroundf,
	.math.llroundl =	llroundl,
	.math.rint =		rint,
	.math.rintf =		rintf,
	.math.rintl =		rintl,
	.math.lrint =		lrint,
	.math.lrintf =		lrintf,
	.math.lrintl =		lrintl,
	.math.llrint =		llrint,
	.math.llrintf =		llrintf,
	.math.llrintl =		llrintl,
	.math.nearbyint =	nearbyint,
	.math.nearbyintf =	nearbyintf,
	.math.nearbyintl =	nearbyintl,

	.math.erf =		erf,
	.math.erff =		erff,
	.math.erfl =		erfl,
	.math.erfc =		erfc,
	.math.erfcf =		erfcf,
	.math.erfcl =		erfcl,
	.math.lgamma =		lgamma,
	.math.lgammaf =		lgammaf,
	.math.lgammal =		lgammal,
	.math.tgamma =		tgamma,
	.math.tgammaf =		tgammaf,
	.math.tgammal =		tgammal,
	.math.pow =		pow,
	.math.powf =		powf,
	.math.powl =		powl,
	.math.sqrt =		sqrt,
	.math.sqrtf =		sqrtf,
	.math.sqrtl =		sqrtl,
	.math.cbrt =		cbrt,
	.math.cbrtf =		cbrtf,
	.math.cbrtl =		cbrtl,
	.math.hypot =		hypot,
	.math.hypotf =		hypotf,
	.math.hypotl =		hypotl,

	.math.sin =		sin,
	.math.sinf =		sinf,
	.math.sinl =		sinl,
	.math.cos =		cos,
	.math.cosf =		cosf,
	.math.cosl =		cosl,
	.math.tan =		tan,
	.math.tanf =		tanf,
	.math.tanl =		tanl,
	.math.asin =		asin,
	.math.asinf =		asinf,
	.math.asinl =		asinl,
	.math.acos =		acos,
	.math.acosf =		acosf,
	.math.acosl =		acosl,
	.math.atan =		atan,
	.math.atanf =		atanf,
	.math.atanl =		atanl,
	.math.atan2 =		atan2,
	.math.atan2f =		atan2f,
	.math.atan2l =		atan2l,
	.math.sinh =		sinh,
	.math.sinhf =		sinhf,
	.math.sinhl =		sinhl,
	.math.cosh =		cosh,
	.math.coshf =		coshf,
	.math.coshl =		coshl,
	.math.tanh =		tanh,
	.math.tanhf =		tanhf,
	.math.tanhl =		tanhl,
	.math.asinh =		asinh,
	.math.asinhf =		asinhf,
	.math.asinhl =		asinhl,
	.math.acosh =		acosh,
	.math.acoshf =		acoshf,
	.math.acoshl =		acoshl,
	.math.atanh =		atanh,
	.math.atanhf =		atanhf,
	.math.atanhl =		atanhl,

	.math.exp =		exp,
	.math.expf =		expf,
	.math.expl =		expl,
	.math.exp2 =		exp2,
	.math.exp2f =		exp2f,
	.math.exp2l =		exp2l,
	.math.expm1 =		expm1,
	.math.expm1f =		expm1f,
	.math.expm1l =		expm1l,
	.math.frexp =		frexp,
	.math.frexpf =		frexpf,
	.math.frexpl =		frexpl,
	.math.ldexp =		ldexp,
	.math.ldexpf =		ldexpf,
	.math.ldexpl =		ldexpl,
	.math.log =		log,
	.math.logf =		logf,
	.math.logl =		logl,
	.math.log2 =		log2,
	.math.log2f =		log2f,
	.math.log2l =		log2l,
	.math.logb =		logb,
	.math.logbf =		logbf,
	.math.logbl =		logbl,
	.math.ilogb =		ilogb,
	.math.ilogbf =		ilogbf,
	.math.ilogbl =		ilogbl,
	.math.log10 =		log10,
	.math.log10f =		log10f,
	.math.log10l =		log10l,
	.math.log1p =		log1p,
	.math.log1pf =		log1pf,
	.math.log1pl =		log1pl,
	.math.modf =		modf,
	.math.modff =		modff,
	.math.modfl =		modfl,
	.math.scalbn =		scalbn,
	.math.scalbnf =		scalbnf,
	.math.scalbnl =		scalbnl,
	.math.scalbln =		scalbln,
	.math.scalblnf =	scalblnf,
	.math.scalblnl =	scalblnl,

	// wide char type functions
	.wide.type.tolower =	towlower,
	.wide.type.toupper =	towupper,

	.wide.type.isalnum =	iswalnum,
	.wide.type.isalpha =	iswalpha,
	.wide.type.isblank =	iswblank,
	.wide.type.iscntrl =	iswcntrl,
	.wide.type.isdigit =	iswdigit,
	.wide.type.isgraph =	iswgraph,
	.wide.type.islower =	iswlower,
	.wide.type.isprint =	iswprint,
	.wide.type.ispunct =	iswpunct,
	.wide.type.isspace =	iswspace,
	.wide.type.isupper =	iswupper,
	.wide.type.isxdigit =	iswxdigit,

	.wide.type.iswctype =	iswctype,
	.wide.type.towctrans =	towctrans,
	.wide.type.wctrans =	wctrans,
	.wide.type.wctype =	wctype,

	// wide IO
	.wide.io.fwide =	fwide,

	.wide.io.fgetc =	fgetwc,
	.wide.io.fgets =	fgetws,
	.wide.io.fputc =	fputwc,
	.wide.io.getchar =	getwchar,
	.wide.io.putc =		putwc,
	.wide.io.putchar =	putwchar,
	.wide.io.ungetc =	ungetwc,

	.wide.io.printf =	wprintf,
	.wide.io.fprintf =	fwprintf,
	.wide.io.sprintf =	swprintf,
	.wide.io.vprintf =	vwprintf,
	.wide.io.vfprintf =	vfwprintf,
	.wide.io.vsprintf =	vswprintf,

	.wide.io.scanf =	wscanf,
	.wide.io.fscanf =	fwscanf,
	.wide.io.sscanf =	swscanf,
	.wide.io.vscanf =	vwscanf,
	.wide.io.vsscanf =	vswscanf,

	// string conversion and monobyte
	.wide.lib.wcstod =	wcstod,
	.wide.lib.wcstof =	wcstof,
	.wide.lib.wcstol =	wcstol,
	.wide.lib.wcstold =	wcstold,
	.wide.lib.wcstoll =	wcstoll,
	.wide.lib.wcstoul =	wcstoul,
	.wide.lib.wcstoull =	wcstoull,

	.wide.lib.mbsinit =	mbsinit,
	.wide.lib.mbrlen =	mbrlen,
	.wide.lib.mbrtowc =	mbrtowc,
	.wide.lib.mbsrtowcs =	mbsrtowcs,
	.wide.lib.wctob =	wctob,
	.wide.lib.btowc =	btowc,
	.wide.lib.wcsrtombs =	wcsrtombs,
	.wide.lib.wcrtomb =	wcrtomb,

	// wide strings
	.wide.str.len =		wcslen,
	.wide.str.cat =		wcscat,
	.wide.str.ncat =	wcsncat,
	.wide.str.xfrm =	wcsxfrm,

	.wide.str.cpy =		wcscpy,
	.wide.str.ncpy =	wcsncpy,

	.wide.str.cmp =		wcscmp,
	.wide.str.ncmp =	wcsncmp,
	.wide.str.coll =	wcscoll,

	.wide.str.chr =		wcschr,
	.wide.str.rchr =	wcsrchr,
	.wide.str.cspn =	wcscspn,
	.wide.str.spn =		wcsspn,
	.wide.str.pbrk =	wcspbrk,
	.wide.str.str =		wcsstr,
	.wide.str.tok =		wcstok,

	// wide memory
	.wide.mem.set =		wmemset,

	.wide.mem.cpy =		wmemcpy,
	.wide.mem.move =	wmemmove,

	.wide.mem.cmp =		wmemcmp,

	.wide.mem.chr =		wmemchr,

	// wide time
	.wide.time.wcsftime =	wcsftime
};
